### ISSUE TITLE
Failed to load a language-ruby-on-rails package grammar

### ISSUE THREAD

**Issue by TimothyLe** [atom/language-ruby-on-rails#57] opened 2017-07-12 06:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [language-ruby-on-rails](https://github.com/atom/language-ruby-on-rails) package 0.25.2

### Stack Trace

Failed to load a language-ruby-on-rails package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Home\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json' in C:\Users\Home\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json

Error: ENOENT: no such file or directory, open 'C:\Users\Home\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-ruby-on-rails\grammars\html (rails).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-ruby-on-rails/grammars/html (rails).json:1:1
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment] 2017-07-13 01:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-13 01:28 UTC
