### ISSUE TITLE
Bug with highlight in case of word wrap 

### ISSUE THREAD

**Issue by freemanoid** [atom/language-ruby-on-rails#35] opened 2015-06-15 06:28 UTC
Here I'm toggling the sidebar. You can see that the 1st line highlights wrongly when it breaks across the lines because of sidebar.

![syntax_bug](https://cloud.githubusercontent.com/assets/180154/8154239/9f1d1440-1340-11e5-98be-fb4f0e45b81a.gif)

**Comment by 50Wliu** [comment] 2015-06-15 11:40
Duplicate of atom/atom#7068, please subscribe there for updates.
(Ignore how it says ES6 highlighting; it looks like the root issue is the same here)

**Closed by 50Wliu** 2015-06-15 11:40 UTC

**Comment by freemanoid** [comment] 2015-06-15 11:42
Great that you noticed that. Thank you.
